### ISSUE TITLE
parse error with XML comment

### ISSUE THREAD

**Issue by Sembiance** [lowlighter/libs#13]
Attempting to parse the attached file [test.svg.txt](https://github.com/lowlighter/xml/files/7558143/test.svg.txt) fails with error:
```
SyntaxError: Expected next sequence to be "-->", got "+--" instead
    at Stream.consume (https://deno.land/x/xml@2.0.1/utils/stream.ts:79:11)
    at Parser.#consume (https://deno.land/x/xml@2.0.1/utils/parser.ts:446:25)
    at Parser.#comment (https://deno.land/x/xml@2.0.1/utils/parser.ts:358:18)
    at Parser.#node (https://deno.land/x/xml@2.0.1/utils/parser.ts:102:47)
    at Parser.#tag (https://deno.land/x/xml@2.0.1/utils/parser.ts:200:35)
    at Parser.#node (https://deno.land/x/xml@2.0.1/utils/parser.ts:104:21)
    at Parser.#tag (https://deno.land/x/xml@2.0.1/utils/parser.ts:200:35)
    at Parser.#node (https://deno.land/x/xml@2.0.1/utils/parser.ts:104:21)
    at Parser.#document (https://deno.land/x/xml@2.0.1/utils/parser.ts:79:45)
    at Parser.parse (https://deno.land/x/xml@2.0.1/utils/parser.ts:21:26)
```

Seems it doesn't like the comment
```
<!--+++++++++++++++++++++-->
```

I've ran the XML through various linters, seems to be valid XML.

**Comment by lowlighter** [comment]
Should be fixed now: https://dash.deno.com/playground/dark-ferret-72

The closing comment token was using a lookbehind, which was making it not actually capturing the last character of comments (in this case a `+`) so when consuming the token there was still a leftover character. It didn't affect ` -->` (when the closing tag was spaced) because it was probably trimmed
https://github.com/lowlighter/xml/blob/4092463566acf82d4129a098159d897ece3a29af/utils/types.ts#L156
